version: '3.9'

services:
  testdb:
    image: postgres:14
    container_name: testdb
    volumes:
      - db-data:/var/lib/postgresql
      - ./database/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - '5555:5432'
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    restart: always
volumes:
  db-data:
