version: '3.9'

services:
  testdb:
    build:
      context: ./database/postgres
      dockerfile: Dockerfile
    container_name: testdb
    ports:
      - '5555:5432'
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  nosqldb:
    build:
      context: ./database/mongodb
      dockerfile: Dockerfile
    container_name: nosqldb
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  # api:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   container_name: api
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - testdb
  #     - nosqldb
  #   environment:
  #     DB_HOST: testdb
  #     DB_PORT: 5432
  #     DB_NAME: testdb
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: postgres
  #     MONGO_DB_NAME: nosqldb
  #     MONGO_INITDB_ROOT_USERNAME: mongodb
  #     MONGO_INITDB_ROOT_PASSWORD: mongodb
  #   restart: always

volumes:
  db-data:
  mongo-data:
